# Generated by Django 6.0.4 on 2026-04-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_bonusresult_criterion_employeeperformance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('head', 'Руководитель компании'), ('manager', 'Менеджер'), ('employee', 'Сотрудник')], default='employee', max_length=10),
        ),
    ]
