# Generated by Django 6.0.4 on 2026-04-14 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterion',
            name='weight',
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.company'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='EmployeeCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_weight', models.FloatField(default=0.0)),
                ('employee_weight', models.FloatField(default=0.0)),
                ('final_weight', models.FloatField(default=0.0)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.criterion')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_criteria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('employee', 'criterion')},
            },
        ),
    ]
