# Generated by Django 6.0.4 on 2026-04-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_remove_criterion_weight_user_position_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeecriterion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employeecriterion',
            name='employee_evaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeecriterion',
            name='manager_evaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeecriterion',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='employeecriterion',
            name='criterion',
        ),
        migrations.RemoveField(
            model_name='employeecriterion',
            name='employee_weight',
        ),
        migrations.RemoveField(
            model_name='employeecriterion',
            name='final_weight',
        ),
        migrations.RemoveField(
            model_name='employeecriterion',
            name='manager_weight',
        ),
    ]
