# Generated by Django 6.0.4 on 2026-04-15 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(default=0.0, verbose_name='Итоговый балл')),
                ('share', models.FloatField(default=0.0, verbose_name='Доля в фонде (0.0 - 1.0)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BonusResult',
        ),
    ]
