# Generated by Django 6.0.4 on 2026-04-16 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0011_alter_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecriterion',
            name='is_individual',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PositionCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название критерия')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_criteria', to='evaluations.position')),
            ],
        ),
    ]
