# Generated by Django 6.0.4 on 2026-04-16 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0012_employeecriterion_is_individual_positioncriterion'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecriterion',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='PairwiseComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('criterion1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c1', to='evaluations.employeecriterion')),
                ('criterion2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c2', to='evaluations.employeecriterion')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
