# Generated by Django 6.0.4 on 2026-04-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0013_employeecriterion_weight_pairwisecomparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='criteria_confirmed',
            field=models.BooleanField(default=False, verbose_name='Критерии подтверждены менеджером'),
        ),
    ]
