# Generated by Django 6.0.4 on 2026-04-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0014_user_criteria_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='weight_manager',
            field=models.FloatField(default=0.6, verbose_name='Вес оценки менеджера'),
        ),
        migrations.AddField(
            model_name='company',
            name='weight_peer',
            field=models.FloatField(default=0.2, verbose_name='Вес оценки коллег'),
        ),
        migrations.AddField(
            model_name='company',
            name='weight_self',
            field=models.FloatField(default=0.2, verbose_name='Вес самооценки'),
        ),
    ]
