# Generated by Django 6.0.4 on 2026-04-18 17:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0018_evaluationphase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationresult',
            options={'ordering': ['-total_score']},
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='month',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Месяц'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='year',
            field=models.PositiveSmallIntegerField(default=2026, verbose_name='Год'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='evaluationresult',
            unique_together={('employee', 'month', 'year')},
        ),
    ]
