# Generated by Django 6.0.4 on 2026-04-18 20:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0019_alter_evaluationresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterionscore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criterionscore',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AddField(
            model_name='evaluationphase',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
