# Generated by Django 6.0.4 on 2026-04-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0020_criterionscore_created_at_criterionscore_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationresult',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
