# Generated by Django 6.0.4 on 2026-04-19 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0021_evaluationresult_is_archived'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluationphase',
            unique_together=set(),
        ),
    ]
