# Generated by Django 6.0.4 on 2026-04-19 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0022_alter_evaluationphase_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='criterionscore',
            unique_together=set(),
        ),
    ]
