# Generated by Django 6.0.4 on 2026-04-19 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0023_alter_criterionscore_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluationresult',
            unique_together=set(),
        ),
    ]
