# Generated by Django 6.0.4 on 2026-04-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0024_alter_evaluationresult_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='bonus_pool',
        ),
    ]
